version: "3.9"
services:
  nginx-container:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./html:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/ssl.crt:/etc/nginx/ssl.crt 
            - ./nginx/ssl.key:/etc/nginx/ssl.key
            
  